# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-18 22:25
from __future__ import unicode_literals

from django.db import migrations
from TodayProject.settings import ALLOWED_HOSTS
from django.contrib.sites.models import Site


# see https://docs.djangoproject.com/fr/1.9/topics/migrations/#data-migrations
def set_sites_arguments(apps, schema_editor):
    site = Site()
    site.domain = ALLOWED_HOSTS[0]
    site.name = ALLOWED_HOSTS[0].split('.')[0]
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_topic'),
    ]

    operations = [
        migrations.RunPython(set_sites_arguments)
    ]
