# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connection', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'Titre')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('image', models.ImageField(default=None, upload_to=b'events/', verbose_name=b'Image')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name=b'Prix en euros')),
                ('address', models.CharField(default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, verbose_name=b'Adresse')),
                ('city', models.ForeignKey(default={b'city_name': b'Paris'}, on_delete=django.db.models.deletion.CASCADE, to='location.City', verbose_name=b'Ville')),
                ('event_planner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connection.EventPlanner', verbose_name=b'annonceur')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name=b'label')),
                ('image', models.ImageField(default=None, upload_to=b'event_types/')),
            ],
            options={
                'verbose_name': 'event type',
                'verbose_name_plural': 'event types',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name=b'note')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'created')),
                ('object_id', models.PositiveIntegerField(verbose_name=b'object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name=b'content type')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_multiple', models.BooleanField(default=False)),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='catho.Event')),
            ],
            options={
                'ordering': ('start_time', 'end_time'),
                'verbose_name': 'occurrence',
                'verbose_name_plural': 'occurrences',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catho.EventType', verbose_name=b'Cat\xc3\xa9gorie'),
        ),
    ]
