# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event planner',
                'verbose_name_plural': 'event planners',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_planner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='catho.EventPlanner', verbose_name='organisateur'),
        ),
    ]
