# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 13:08
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connection', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to=b'events/', verbose_name=b'Image')),
                ('title', models.CharField(default=None, max_length=100, null=True, verbose_name=b'Titre')),
                ('description', models.TextField(default=None, null=True, verbose_name=b'Description')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name=b'Prix en euros')),
                ('contact', models.CharField(blank=True, default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, null=True, verbose_name=b'Coordonn\xc3\xa9es du contact \xc3\xa9ventuel')),
                ('website', models.CharField(blank=True, default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, null=True, verbose_name=b"Lien vers le site officiel de l'\xc3\xa9v\xc3\xa9nement")),
                ('address', models.CharField(default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, verbose_name=b'Adresse')),
                ('event_planner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connection.EnjoyTodayUser', verbose_name=b'annonceur')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=b'autres', max_length=50, verbose_name=b'label')),
                ('image', models.ImageField(default=None, null=True, upload_to=b'event_types/')),
                ('topic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Topic', verbose_name=b'Thematique')),
            ],
            options={
                'verbose_name': 'event type',
                'verbose_name_plural': 'event types',
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_multiple', models.BooleanField(default=False)),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='topic.Event')),
            ],
            options={
                'ordering': ('start_time', 'end_time'),
                'verbose_name': 'occurrence',
                'verbose_name_plural': 'occurrences',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='topic.EventType', verbose_name=b'Cat\xc3\xa9gorie'),
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sites.Site'),
        ),
    ]
