# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-13 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='website',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 13, 20, 9, 9, 74568), verbose_name=b'Date de cr\xc3\xa9ation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default=None, help_text=b"Donner l'adresse postale <em>au sens de google</em>", max_length=150, verbose_name=b'Adresse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, default=None, help_text=b"Informations sur l'organisateur <em>officiel<\\em> de l'\xc3\xa9v\xc3\xa9nement", max_length=150, verbose_name=b'D\xc3\xa9tails organisateur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=None, help_text=b"Description de l'\xc3\xa9v\xc3\xa9nement. Ajouter \xc3\xa9galement tout d\xc3\xa9tails utiles", verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_planner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='connection.EnjoyTodayUser', verbose_name=b'annonceur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=None, help_text=b"Cat\xc3\xa9gorie \xc3\xa0 laquelle est rattach\xc3\xa9 l'\xc3\xa9v\xc3\xa9nement", on_delete=django.db.models.deletion.SET_DEFAULT, to='topic.EventType', verbose_name=b'Cat\xc3\xa9gorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, help_text=b"image affich\xc3\xa9e pour l'\xc3\xa9v\xc3\xa9nement", upload_to=b'events/', verbose_name=b'Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, default=None, help_text=b'Conditions tarifaires', max_length=300, verbose_name=b'Prix'),
        ),
        migrations.AlterField(
            model_name='event',
            name='public_transport',
            field=models.CharField(blank=True, default=None, help_text=b'Arr\xc3\xaat de m\xc3\xa9tro,...', max_length=150, verbose_name=b'Transport en commun'),
        ),
        migrations.AlterField(
            model_name='event',
            name='site',
            field=models.ForeignKey(default=None, help_text=b"ville dans laquelle sera post\xc3\xa9 l'\xc3\xa9v\xc3\xa9nement", on_delete=django.db.models.deletion.SET_DEFAULT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, help_text=b"Titre affich\xc3\xa9 pour l'\xc3\xa9v\xc3\xa9nement", max_length=100, verbose_name=b'Titre'),
        ),
    ]
