# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_planner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connection.EnjoyTodayUser', verbose_name=b'annonceur'),
        ),
    ]
