# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='public_transport',
        ),
    ]
