# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-18 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default=None, help_text=b"Donner l'adresse postale <u>au sens de google</u>", max_length=150, verbose_name=b'Adresse *'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=None, help_text=b"Description de l'\xc3\xa9v\xc3\xa9nement. Ajouter \xc3\xa9galement tout d\xc3\xa9tails utiles", verbose_name=b'Description *'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, help_text=b"Photo de l'\xc3\xa9v\xc3\xa9nement", upload_to=b'events/', verbose_name=b'Image *'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=None, help_text=b"Ville ou agglom\xc3\xa9ration o\xc3\xb9 a lieu l'\xc3\xa9v\xc3\xa9nement", on_delete=django.db.models.deletion.SET_DEFAULT, to='location.City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='public_transport',
            field=models.CharField(blank=True, default=None, help_text=b'Transports, parkings, ...', max_length=150, verbose_name=b'Accessibilit\xc3\xa9'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, help_text=b'Choisissez un nom court et clair', max_length=100, verbose_name=b"Nom de l'\xc3\xa9v\xc3\xa9nement *"),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default=b'spi', max_length=50, verbose_name=b'Th\xc3\xa9matique'),
        ),
    ]
