# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20160823_1438'),
        ('topic', '0002_auto_20160620_1938'),
    ]

    operations = [
    ]
