# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, null=True, verbose_name=b'Coordonn\xc3\xa9es du contact \xc3\xa9ventuel'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.CharField(blank=True, default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, null=True, verbose_name=b"Lien vers le site officiel de l'\xc3\xa9v\xc3\xa9nement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_planner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connection.EnjoyTodayUser', verbose_name=b'annonceur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='topic.EventType', verbose_name=b'Cat\xc3\xa9gorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=b'events/', verbose_name=b'Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name=b'Titre'),
        ),
    ]
