# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20160904_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_transport',
            field=models.CharField(default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, verbose_name=b'Arr\xc3\xaat transport en commun (m\xc3\xa9tro,...)'),
        ),
    ]
