# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_event_public_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public_transport',
            field=models.CharField(blank=True, default=b'non pr\xc3\xa9cis\xc3\xa9', max_length=150, null=True, verbose_name=b'Arr\xc3\xaat transport en commun (m\xc3\xa9tro,...)'),
        ),
    ]
